### ISSUE TITLE
Warning when installing FMPy via poetry

### ISSUE THREAD

**Issue by tbukic** [CATIA-Systems/FMPy#603] opened 2023-10-03 19:56 UTC
Poetry version: 1.5.1
System is Ubuntu on WSL2: 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux

Here is the warning:
```
Warning: Validation of the RECORD file of FMPy-0.3.16-py3-none-any.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/cswrapper/cswrapper.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/cswrapper/cswrapper.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/remoting/linux64/server_tcp is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/remoting/linux64/client_tcp.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-linux/sundials_cvode.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-linux/sundials_nvecserial.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-linux/sundials_sunlinsoldense.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-linux/sundials_sunmatrixdense.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-darwin/sundials_sunlinsoldense.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-darwin/sundials_cvode.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-darwin/sundials_nvecserial.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/sundials/x86_64-darwin/sundials_sunmatrixdense.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/fmucontainer/binaries/linux64/FMUContainer.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/fmucontainer/binaries/darwin64/FMUContainer.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/logging/linux64/logging.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/logging/darwin64/logging.dylib is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/modelica/FMI/Resources/Library/linux64/libModelicaFMI.so is not mentioned in RECORD
In /home/<redacted>/.cache/pypoetry/artifacts/7c/08/69/c6289613ebd11b47a638d919fdaeebcd5d54ed896ea25650307fe2b331/FMPy-0.3.16-py3-none-any.whl, fmpy/modelica/FMI/Resources/Library/darwin64/libModelicaFMI.dylib is not mentioned in RECORD
```

**Comment by famura** [comment] 2023-10-04 10:11
@tbukic  I am getting the same warning for weeks now. Thanks for opening this issue.

**Comment by t-sommer** [comment] 2023-10-05 08:22
Closing as duplicate of #535.

**Closed by t-sommer** 2023-10-05 08:22 UTC
