### ISSUE TITLE
Simulating FMU crashes the python interpreter on FMU.terminate()

### ISSUE THREAD

**Issue by filip-jezek** [CATIA-Systems/FMPy#148] opened 2020-06-18 13:01 UTC
Probably related to #147 but slightly different and now a blocker. Happens for some FMUs only.

Same as before, it results in crash of python interpreter before results are handed from fmpy.simulate_fmu for certain FMU2 CS exported from Dymola 2021

When stepping through, all FMI steps are taken, but at fmu.terminate() the execution suddenly stops.

Code to reproduce: https://gist.github.com/filip-jezek/ee9d49ac6b2f038175cb7aa45971ceee
Same local settings as in #147 

Thanks for any help.
F/

**Comment by filip-jezek** [comment] 2020-06-18 13:05
FMPy.gui does simulate this particular FMU correctly, however on pressing the square stop button it crashes as well.

**Comment by t-sommer** [comment] 2020-06-22 09:22
@KarlWernersson, can you take a look at this?

**Comment by t-sommer** [comment] 2020-06-22 09:28
@filip-jezek, to nail down the problem, can you try to export the model with another solver (e.g. CVode) and another version of Dymola?

**Comment by filip-jezek** [comment] 2020-06-23 15:18
The issue arises with CVODE solver, but now I have tested export with Dymola solvers with same behavior. The model was not simulating in previous Dymola in CVODE at all, so I cannot reproduce there.

Here I save-totalled the modelica sources for you: https://gist.github.com/filip-jezek/66f36062c70b0f2225cbe4eefa8ec01f


Thank you for any help!
F/

**Comment by KarlWernersson** [comment] 2020-09-25 10:27
Hi Filip sorry for the delay.
Is it possible that you generated your model with Advanced.SparseActivate = true?
I am able to reproduce the problem if this flag is activated, if not I am unable to reproduce it.

**Comment by filip-jezek** [comment] 2020-09-25 15:53
Karl, thank you for your reply, even a late one :) 

Yes, I am using this option to speed up the models a bit - it drops the simulation time by about 25%. The speed up is not as crucial, but it is nice to have, especially when the runtime of our models is about minute and we need to run a complex optimization tasks.

Its great to know that there is a workaround, but still, do you see it possible to fix or better to get rid of this option?

Thanks a bunch,
Filip

**Comment by KarlWernersson** [comment] 2020-09-27 08:37
Hi Filip, I am currently investigating the issue and will correct it for Dymola 2021 release.
Is that sufficient for you or do you need a fix pack for Dymola 2020x?
/Kalle

**Comment by filip-jezek** [comment] 2020-09-28 20:21
Karl, I do not need it at the moment, as I had to take a different route, but can I contact you when the need arises, if its before 2022 release?

**Comment by t-sommer** [comment] 2020-09-28 20:23
I'm closing this issue, as it's not related to FMPy.

**Closed by t-sommer** 2020-09-28 20:23 UTC
