### ISSUE TITLE
Error when running fmpy on Linux for simple fmu

### ISSUE THREAD

**Issue by SchmJo** [CATIA-Systems/FMPy#435] opened 2022-08-10 11:38 UTC
For me issue #330 is still not solved. When trying to run a simple fmu on Ubuntu 20.04 with Python 3.9 I obtain errors. I am running
```console
fmpy simulate SinusGenerator.fmu
```
on `SinusGenerator.fmu`, which I obtain from running
```console
pythonfmu build -f sinusGenerator.py
```
on the file `sinusGenerator.py`
```python
from pythonfmu import Fmi2Causality, Fmi2Slave, Real
import numpy as np


class SinusGenerator(Fmi2Slave):

    author = "John Doe"
    description = "A simple description"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.waveHeight = 0.0
        self.register_variable(
            Real("waveHeight", causality=Fmi2Causality.output))

        self.freq = 1.0
        self.register_variable(
            Real("freq", causality=Fmi2Causality.local))

    def do_step(self, current_time, step_size):
        self.waveHeight = np.sin(self.freq * current_time)
        return True
```
The error is
```
Traceback (most recent call last):
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi1.py", line 161, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonas/.venv/h2digital/bin/fmpy", line 8, in <module>
    sys.exit(main())
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/command_line.py", line 161, in main
    result = simulate_fmu(args.fmu_filename,
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/simulation.py", line 738, in simulate_fmu
    fmu = instantiate_fmu(unzipdir, model_description, fmi_type, visible, debug_logging, logger, fmi_call_logger, None, early_return_allowed, use_event_mode)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/simulation.py", line 819, in instantiate_fmu
    fmu = FMU2Slave(**fmu_args)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi2.py", line 524, in __init__
    super(FMU2Slave, self).__init__(**kwargs)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi2.py", line 85, in __init__
    super(_FMU2, self).__init__(**kwargs)
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/fmi1.py", line 163, in __init__
    raise Exception("Failed to load shared library %s. %s" % (libraryPath, e))
Exception: Failed to load shared library /tmp/tmp0w730amm/binaries/linux64/SinusGenerator.so. libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```
The solution suggested in #330 is
```console
fmpy compile SinusGenerator.fmu
```
but this gives
```
Compiling platform binary...
/tmp/tmp07fixcfx/sources
gcc -c -fPIC -I. -I/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/c-code  headers/pythonfmu/PySlaveInstance.hpp headers/pythonfmu/PyState.hpp headers/cppfmu/cppfmu_common.hpp headers/cppfmu/cppfmu_cs.hpp cpp/cppfmu_cs.cpp cpp/fmi_functions.cpp cpp/PySlaveInstance.cpp CMakeLists.txt && gcc -static-libgcc -shared -oSinusGenerator.so *.o -lm
headers/pythonfmu/PySlaveInstance.hpp:5:10: fatal error: cppfmu/cppfmu_cs.hpp: No such file or directory
    5 | #include "cppfmu/cppfmu_cs.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
headers/pythonfmu/PyState.hpp:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
headers/cppfmu/cppfmu_common.hpp:24:14: fatal error: fmi/fmi2Functions.h: No such file or directory
   24 | #    include "fmi/fmi2Functions.h"
      |              ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from headers/cppfmu/cppfmu_cs.hpp:9:
headers/cppfmu/cppfmu_common.hpp:24:14: fatal error: fmi/fmi2Functions.h: No such file or directory
   24 | #    include "fmi/fmi2Functions.h"
      |              ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/cppfmu_cs.cpp:6:10: fatal error: cppfmu/cppfmu_cs.hpp: No such file or directory
    6 | #include "cppfmu/cppfmu_cs.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/fmi_functions.cpp:6:10: fatal error: cppfmu/cppfmu_cs.hpp: No such file or directory
    6 | #include "cppfmu/cppfmu_cs.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
cpp/PySlaveInstance.cpp:2:10: fatal error: pythonfmu/PySlaveInstance.hpp: No such file or directory
    2 | #include "pythonfmu/PySlaveInstance.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/jonas/.venv/h2digital/bin/fmpy", line 8, in <module>
    sys.exit(main())
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/command_line.py", line 99, in main
    compile_platform_binary(filename=args.fmu_filename,
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/util.py", line 906, in compile_platform_binary
    binary = compile_dll(model_description=model_description,
  File "/home/jonas/.venv/h2digital/lib/python3.9/site-packages/fmpy/util.py", line 880, in compile_dll
    raise Exception('Failed to compile shared library')
Exception: Failed to compile shared library
```
Can anybody help? Thanks a lot!

**Comment by t-sommer** [comment] 2022-08-10 19:55
Closing as duplicate of #348.

**Closed by t-sommer** 2022-08-10 19:55 UTC

**Comment by SchmJo** [comment] 2022-08-11 06:21
To be honest, I still don't understand what I should do, even after reading #348. And I am actually running Python 3.9

**Comment by SchmJo** [comment] 2022-08-15 07:03
I figured it out! In my case, the following worked:

1. Install fmpy in a virtual environment
2. Inside the venv, enter the directory `.../site-packages/pythonfmu/pythonfmu-export`
3. Change the file `CMakeLists.txt`: Replace `find_package(Python3 COMPONENTS Interpreter Development REQUIRED)` by `find_package(Python3 COMPONENTS Development REQUIRED)`
4. Run the `cmake` build:
```console
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

This creates a new binary for `pythonfmu` that did the job in my case.

**Comment by siown** [comment] 2022-09-13 07:40
In addition, I did the third and fourth steps in the directory /home/qi/miniconda3/lib/python3.8/site-packages/pythonfmu/pythonfmu-export, it worked as well.

> I figured it out! In my case, the following worked:
> 
> 1. Install fmpy in a virtual environment
> 2. Inside the venv, enter the directory `.../site-packages/pythonfmu/pythonfmu-export`
> 3. Change the file `CMakeLists.txt`: Replace `find_package(Python3 COMPONENTS Interpreter Development REQUIRED)` by `find_package(Python3 COMPONENTS Development REQUIRED)`
> 4. Run the `cmake` build:
> 
> ```
> mkdir build
> cd build
> cmake .. -DCMAKE_BUILD_TYPE=Release
> cmake --build .
> ```
> 
> This creates a new binary for `pythonfmu` that did the job in my case.

**Comment by DanielSmetankin** [comment] 2023-04-26 07:47
Hi,
I can't seem to find the virtual environment you mentioned.
Where is it located exactly? 
I installed fmpy with pip using the terminal in vscode. 
I am using Ubuntu 18.04 on an NVDIA jetson xavier nx.
Thanks for all the previous insights!

**Comment by DanielSmetankin** [comment] 2023-04-26 07:49
Hi, 
I can't seem to find to folder pythonfmu only fmpy.
Do you have any idea what the cause could be?
I am using Ubuntu 18.04 on an NVDIA jetson xavier nx.
Thanks for all the previous insights!
