### ISSUE TITLE
String datatype with Start value not working with fmpy, error in Schema

### ISSUE THREAD

**Issue by PRAVEENFrmBOSCH** [CATIA-Systems/FMPy#600] opened 2023-09-20 09:37 UTC
**ModelDescription.xml**  Sample
<String name="char_input" valueReference="26" causality="input" variability="discrete" initial="exact" declaredType="string" **start="1"** intermediateUpdate="false"/>

model_description.py : read_model_description() line no 469 

**STACK:**

Traceback (most recent call last):
  File "C:\Users\Desktop\FMI3_FMPy\FMI3_Test.py", line 247, in <module>
    simulate_custom_input()
  File "C:\Users\Desktop\FMI3_FMPy\FMI3_Test.py", line 33, in simulate_custom_input
    model_description = read_model_description(fmu_filename)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "C:\Users\Programs\Python\Python311\Lib\site-packages\fmpy\model_description.py", line 469, in read_model_description
    raise ValidationError(problems)**
fmpy.model_description.ValidationError: Failed to validate modelDescription.xml:
- ERROR (line 63, column 0): Element 'String', attribute 'start': The attribute 'start' is not allowed.

**Comment by t-sommer** [comment] 2023-09-25 21:46
Closing as duplicate of https://github.com/modelica/Reference-FMUs/issues/405.

**Closed by t-sommer** 2023-09-25 21:46 UTC
Labels: invalid
