### ISSUE TITLE
CVode Error depending on combination of output_interval and stop_time

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#12] opened 2018-01-15 18:51 UTC
For the bouncingBall.fmu (64bit Windows) from the FMU-SDK 2.0.5 I get an error with FMPy when simulating (tested with the development branch for certain combinations of output_interval and stop_time.
For example for
>>> result = simulate_fmu(fmu, output_interval=0.01, stop_time=1)

I get: 
[CVODE ERROR]  CVode
  At t = 0.996514, mxstep steps taken before reaching tout.

....
However for
>>> result = simulate_fmu(fmu, output_interval=0.001, stop_time=1)
There is no error.

[bouncingBall.zip](https://github.com/CATIA-Systems/FMPy/files/1632705/bouncingBall.zip)

**Comment by t-sommer** [comment] 2018-01-16 11:06
The attached FMU does not specify a relative tolerance (no `<DefaultExperiment>` in the modelDescription.xml) so the default value of `1e-5` is used which is too restrictive for this model. However you can set the relative tolerance explicitly:

`simulate_fmu('bouncingBall.fmu', relative_tolerance=1e-4, output_interval=0.01, stop_time=1)`

**Comment by chrbertsch** [comment] 2018-01-16 19:14
The error of good solver like CVODE should go to zero as the tolerance is reduced. It is good practice to perform a convergence study for a simulation, step by step reducing the tolerance. Thus I do not understand why a tolerance of 1e-5 should be too small. 
The error does not occur for 

`result = simulate_fmu(fmu, output_interval=0.001, stop_time=1)`, i.e with a tolerance of 1e-5.

I do not see the reason, why the output interval influences the solution.
Thus for me the issue is not solved.

**Comment by t-sommer** [comment] 2018-01-16 19:50
This seems to be an issue that is related to CVode and has been discussed [here](http://sundials.2283335.n4.nabble.com/Error-quot-mxstep-steps-taken-before-reaching-tout-quot-td3239188.html). The proposed solution is to

> [...] either increase the max step parameter or reduce the tout distances.

We could expose `CVodeSetMaxStep()` and make the value adjustable.

**Comment by chrbertsch** [comment] 2018-01-16 20:39
Yes, this would be vrey good. Is it possible also to parse the error of CVode and give the user a hint what do in this case.

**Comment by t-sommer** [comment] 2018-01-17 15:00
It's possible to handle the error by setting an error handling function:

`typedef void (*CVErrHandlerFn)(int error_code, const char *module, const char *function,  char *msg, void *user_data);`

For the example above you would get:

`error_code: -1 (CV_TOO_MUCH_WORK)`
`module: "CVODE"`
`function: "CVode"`
`msg: "At t = 0.00499, mxstep steps taken before reaching tout."`

What would be the hint in this case?

**Comment by t-sommer** [comment] 2018-01-17 17:14
The problem was actually shadowed by a wrong positional argument to the CVodeSolver constructor that has been fixed in d52a24d8. Please reopen if you can still reproduce the problem.

**Closed by t-sommer** 2018-01-17 17:14 UTC
