### ISSUE TITLE
FMPy on RPI3

### ISSUE THREAD

**Issue by MikeBarth** [CATIA-Systems/FMPy#9] opened 2018-01-10 13:44 UTC
Hi,
I tried to launch FMPy on a Raspberry Pi model b. The installation was successful and I managed to load the 32bit LINUX FMU (Model Exchange). I can also display the model information. As soon as I start simulating, I get the error message that the shared object file cannot be found. 
![image](https://user-images.githubusercontent.com/35299755/34775627-23e5ca4c-f614-11e7-8c73-940a8569e9a1.png)
But i can see the unzipped *.so file in that folder ? Any ideas?

Mike

**Comment by t-sommer** [comment] 2018-01-10 14:08
Does the FMU support linux32? You could try https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/FMI_2.0/CoSimulation/linux32/MapleSim/2015.2/Rectifier

**Comment by t-sommer** [comment] 2018-01-10 14:15
The problem seems to be the CVode solver which comes as an .so file (but only for linux64). To work around this problem you could:

- use a co-simulation FMU or
- use `simulate_fmu('Rectifier.fmu', solver='Euler')`

**Comment by t-sommer** [comment] 2018-01-10 14:49
The shared libraries in binaries/linux32/ are most likely compiled for x86 (PC) but the Raspberry Pi 3 has an ARMv8 chip. You could try to build the shared library from an FMU that provides source code (e.g. https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/FMI_2.0?order=name#CoSimulation/win64/Dymola/2017/Rectifier).

**Comment by MikeBarth** [comment] 2018-01-10 14:58
Hello Torsten,

thank you for your quick reply.
The first idea: use simulate_fmu('Rectifier.fmu', solver='Euler') did not work.

How do I build the shared object lib from the example you linked? And how do I get the needed FMU from that?

Best Regards
Mike



Von: Torsten Sommer [mailto:notifications@github.com]
Gesendet: Mittwoch, 10. Januar 2018 15:50
An: CATIA-Systems/FMPy <FMPy@noreply.github.com>
Cc: Barth, Mike <mike.barth@hs-pforzheim.de>; Author <author@noreply.github.com>
Betreff: Re: [CATIA-Systems/FMPy] FMPy on RPI3 (#9)


The shared libraries in binaries/linux32/ are most likely compiled for x86 (PC) but the Raspberry Pi 3 has an ARMv8 chip. You could try to build the shared library from an FMU that provides source code (e.g. https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/FMI_2.0?order=name#CoSimulation/win64/Dymola/2017/Rectifier).

**Comment by MikeBarth** [comment] 2018-01-10 15:12
Co-Simulation models (linux32) result in the same problem.

Von: Torsten Sommer [mailto:notifications@github.com]
Gesendet: Mittwoch, 10. Januar 2018 15:08
An: CATIA-Systems/FMPy <FMPy@noreply.github.com>
Cc: Barth, Mike <mike.barth@hs-pforzheim.de>; Author <author@noreply.github.com>
Betreff: Re: [CATIA-Systems/FMPy] FMPy on RPI3 (#9)


Does the FMU support linux32? You could try https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/FMI_2.0/CoSimulation/linux32/MapleSim/2015.2/Rectifier

**Comment by chrbertsch** [comment] 2018-01-10 20:22
The problem is, that "linux32" in fact means "Linux32 on an Intel platform".
The binaries folder name for Linux on Raspi3 is not yet standardized, see the discussion here.
I prototypically created and simulated FMUs for Raspi 3 with a fork of the FMU-SDK https://github.com/chrbertsch/FMUSDK_fork using the preliminary binaries folder name "linux-armv7l".
So one could either adapt FMPy to support that binaries folder name on a Raspi, or rename the binaries folder create from the FMU-SDK-fork to "linux32" as a quick and dirty solution.

**Comment by t-sommer** [comment] 2018-01-10 21:30
Just download and extract [Rectifier.fmu](https://trac.fmi-standard.org/export/HEAD/branches/public/Test_FMUs/FMI_2.0/CoSimulation/win64/Dymola/2017/Rectifier/Rectifier.fmu) (it's a ZIP archive with a different file extension). Inside you'll find a `sources` folder that contains the C sources and a `documentation` folder that contains some basic instructions. You'll also need the FMI header files you can download [here](https://svn.modelica.org/fmi/branches/public/specifications/v2.0/FMI_for_ModelExchange_and_CoSimulation_v2.0.zip).

**Comment by t-sommer** [comment] 2018-01-12 13:26
I'm closing this issue since it's not really a problem that can be solved in FMPy.

**Closed by t-sommer** 2018-01-12 13:26 UTC

**Comment by chrbertsch** [comment] 2018-01-18 19:42
@MikeBarth : how did you install FMPy on Raspi? I failed with Miniconda due to several reasons (related due to platform, missing packages, compile errors, ....)
Do you use Miniconda? Which version of Python do you use? How do you install missing packages and fmpy?
Thanks in advance.
P..S.: You could now try out Source Code FMU from the development branch, see https://github.com/CATIA-Systems/FMPy/blob/develop/tests/test_c_code.py

**Comment by MikeBarth** [comment] 2018-01-19 09:31
I am using the HOMEGEAR System on my PI which is a very performant version of Raspbian. You can find it here:

https://homegear.eu/

The installation runs with Python3 PIP without problems. Do you think we could try running FMUS on the PI together?


Von: chrbertsch [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. Januar 2018 20:45
An: CATIA-Systems/FMPy <FMPy@noreply.github.com>
Cc: Barth, Mike <mike.barth@hs-pforzheim.de>; Mention <mention@noreply.github.com>
Betreff: Re: [CATIA-Systems/FMPy] FMPy on RPI3 (#9)


@MikeBarth<https://github.com/mikebarth> : how did you install FMPy on Raspi? I failed with Miniconda due to several reasons (related due to platform, missing packages, compile errors, ....)
Do you use Miniconda? Which version of Python do you use? How do you install missing packages and fmpy?
Thanks in advance.
P..S.: You could now try out Source Code FMU from the development branch, see https://github.com/CATIA-Systems/FMPy/blob/develop/tests/test_c_code.py

**Comment by t-sommer** [comment] 2018-01-31 16:42
I've added a [short tutorial](https://github.com/CATIA-Systems/FMPy/wiki/RaspberryPi) that shows how to compile and simulate source code FMUs on a Raspberry Pi.

**Comment by MikeBarth** [comment] 2018-02-01 13:00
Works perfect. Only the OpenModelica examples do not work. Could please check if they work on your system?
https://trac.fmi-standard.org/browser/branches/public/Test_FMUs/FMI_2.0/CoSimulation/c-code/OpenModelica/v1.11.0?order=name


Von: Torsten Sommer [mailto:notifications@github.com]
Gesendet: Mittwoch, 31. Januar 2018 17:43
An: CATIA-Systems/FMPy <FMPy@noreply.github.com>
Cc: Barth, Mike <mike.barth@hs-pforzheim.de>; Mention <mention@noreply.github.com>
Betreff: Re: [CATIA-Systems/FMPy] FMPy on RPI3 (#9)


I've added a short tutorial<https://github.com/CATIA-Systems/FMPy/wiki/RaspberryPi> that shows how to compile and simulate source code FMUs on a Raspberry Pi.

**Comment by t-sommer** [comment] 2018-02-01 15:31
The OpenModelica FMUs are missing a `<SourceFiles>` section in the modelDescription.xml as required by the [FMI 2.0 Specification](https://svn.modelica.org/fmi/branches/public/specifications/v2.0/FMI_for_ModelExchange_and_CoSimulation_v2.0.pdf) (page 66) for source code FMUs.
