### ISSUE TITLE
OpenModelica FMUs failed to load

### ISSUE THREAD

**Issue by manasdas17** [CATIA-Systems/FMPy#171] opened 2020-09-24 07:10 UTC
Co-simulation FMU from OpenModelica has some issues in FMPy. The erroe shown as **Failed to load the FMU as the unit "V" of variable "C1.vinternal" (line 181) is not defined**

**Comment by t-sommer** [comment] 2020-09-24 08:47
This is a duplicate of #113.

**Closed by t-sommer** 2020-09-24 08:47 UTC
