### ISSUE TITLE
Not enough storage error

### ISSUE THREAD

**Issue by Flancis** [CATIA-Systems/FMPy#22] opened 2018-02-21 13:16 UTC
Hi, I have a very complicated FMU model. Sometimes when I simulate the model using the template `custom_input.py`, it gives some errors. However, when I reopen the Spyder console, the errors disappeared. Anyway, part of the errors are as follows.

  File "D:\Software\Miniconda3\envs\py36_32\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\Software\Miniconda3\envs\py36_32\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:\Software\Miniconda3\envs\py36_32\lib\site-packages\fmpy\fmi2.py", line 386, in __init__
    super(FMU2Slave, self).__init__(**kwargs)

  File "D:\Software\Miniconda3\envs\py36_32\lib\site-packages\fmpy\fmi2.py", line 84, in __init__
    super(_FMU2, self).__init__(**kwargs)

  File "D:\Software\Miniconda3\envs\py36_32\lib\site-packages\fmpy\fmi1.py", line 131, in __init__
    self.dll = cdll.LoadLibrary(libraryPath)

  File "D:\Software\Miniconda3\envs\py36_32\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)

  File "D:\Software\Miniconda3\envs\py36_32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 8] Not enough storage is available to process this command

**Comment by t-sommer** [comment] 2018-02-21 14:30
Maybe you run out of memory when loading the DLL. From the environment name `py36_32` I assume you're using a 32-bit Python. Have you tried with a 64-bit Python?

**Comment by Flancis** [comment] 2018-02-21 14:57
Yes, I am using the 32-bit Python because the solver DLL is limited to 32 bit. Like I mentioned previously, the errors now disappeared in the 32-bit Python. Since the code now works fine in the 32-bit Python, it is also normal in the 64-bit Python now. Not sure if the problem will happen again though.

**Comment by t-sommer** [comment] 2018-02-22 07:32
I'm closing this as the problem does not seem to be caused by FMPy. Please re-open if you can provide a reproducible test case.

**Closed by t-sommer** 2018-02-22 07:32 UTC
