### ISSUE TITLE
Axes not displayed correctly

### ISSUE THREAD

**Issue by chrbertsch** [CATIA-Systems/FMPy#59] opened 2018-11-19 12:11 UTC
Simulation the attached FMU with the GUI (using fmpy 2.7.0, on Windoes10 64bit, using Anaconda Python 3.7), the axes are not displayed correctly, see attached Screenshot. Especially, the the bouncing byll should reflect at h=0.
[fmu_bBRef.fmu.zip](https://github.com/CATIA-Systems/FMPy/files/2595198/fmu_bBRef.fmu.zip)
![image](https://user-images.githubusercontent.com/16363372/48706436-8f1b0a00-ebfc-11e8-902f-61af0e6eacdd.png)

**Comment by t-sommer** [comment] 2018-11-19 12:54
The event update of the `bouncingBall` model has been fixed in https://github.com/qtronic/fmusdk/commit/8ded85a929a78e78e3dc50d0a7477138ba065550. Have you applied this change to the above FMU?

**Comment by chrbertsch** [comment] 2018-11-19 12:59
No, but the display problem is independent of the FMU, see e.g. the attached screenshot which also should start at zero. 
![image](https://user-images.githubusercontent.com/16363372/48708621-5468a000-ec03-11e8-8ccf-74fd813defdb.png)

**Comment by t-sommer** [comment] 2018-11-19 13:01
Looks like this is due to `NaN` or `Inf` in the result. Can you reproduce this result with the latest version of the original bouncingBall.fmu from the FMU SDK?

**Comment by chrbertsch** [comment] 2018-11-19 13:10
I get wrong axes for any FMU (FMU-SDK, Dymola, Simulink-via-FMI-Kit, ....).  I also saved the plotted results as CSV and there are no NaNs or Infs,

**Comment by chrbertsch** [comment] 2018-11-19 13:33
Nothing special: 

I installed fmypy via conda (due to a technical limitation I have to download the conda package for fmpy 0.2.7 manually )
conda create -n fmpytest python=3.7 anaconda; activate fmpytest);  
install fmpy 0.2.6 via conda (conda install fmpy) to install the right dependencies;  
then uninstall fmpy (conda remove fmpy), 
download fmpy 0.2.7  from https://anaconda.org/conda-forge/fmpy/files and install it via conda install c:\Users\cbt2si\Downloads\fmpy-0.2.7-py36_0.tar.bz2

Then I just load any fmy, simulate and plot ...

**Comment by t-sommer** [comment] 2018-11-19 13:42
I've tested the installation with `pip` and `conda`. They both work fine for me. Maybe you can try it again on a different machine:

```
conda create -q -n py37_64 -c anaconda python=3.7 dask lxml matplotlib numpy pathlib pyqt pyqtgraph pywin32 requests
activate py37_64
conda install -c conda-forge --no-deps fmpy
python -m fmpy.gui
```

**Comment by chrbertsch** [comment] 2018-11-19 19:18
The problem is away on my computer (Lenovo T480) if I only use the built-in monitor. 
I reproducibly get the problem described above when connect an additional monitor with a different (extended Display)  and display the fmpy-gui there. I can move the fmpy-gui from one monitor to the other and the problems appears and disappers ...

**Comment by chrbertsch** [comment] 2018-11-19 20:14
I cannot reproduce the problem on another (private) laptop (Acer Aspire 7, Win-10 64bit) ....

**Comment by t-sommer** [comment] 2018-11-20 20:00
Can you try to run the PyQtGraph examples?

```
python -m pyqtgraph.examples
```

I assume it's a problem with the upstream libraries Qt / PyQtGraph.

**Comment by chrbertsch** [comment] 2018-11-20 20:50
Yes I get similar problems with axes e.g. with the example "Crosshair / Mouse interaction" on an extended display.
![image](https://user-images.githubusercontent.com/16363372/48801777-87975600-ed0d-11e8-98fa-08fb5931958e.png)

On the command line I get warnings:
```
(fmpytest) C:\WINDOWS\system32>python -m pyqtgraph.examples
C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpytest\lib\runpy.py:125: RuntimeWarning: 'pyqtgraph.examples.__main__' found in sys.modules after import of package 'pyqtgraph.examples', but prior to execution of 'pyqtgraph.examples.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Using PyQt5 (default graphics system)
C:\Users\cbt2si\AppData\Local\conda\conda\envs\fmpytest\lib\site-packages\pyqtgraph\functions.py:1276: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  filtered = filtered[sl]
```
Are they related to the problem?

I think the problem is adressed in  https://stackoverflow.com/questions/45108069/pyqtgraph-axes-not-displaying-correctly . Could the first mentioned solution be applied?

**Comment by t-sommer** [comment] 2018-12-04 15:24
@chrbertsch, I have no setup available where I can verify the proposed fixed. Can you try it on your machine and let us know if it works?

**Comment by chrbertsch** [comment] 2019-01-10 20:03
I would test it. Can I do this with a version of fmpy installed with Anaconda (how to I find the file?) or do I have to install it directly from github? Thanks!

**Comment by t-sommer** [comment] 2019-01-10 20:06
Any recent version of FMPy will do. How you install it does not matter. You can run

```
import fmpy
print(fmpy.__file__)
```

to find out where you installed it.

**Comment by chrbertsch** [comment] 2019-01-10 20:55
OK, got it. 
What is meant with " Qt GUI event loop" in 
>The following line may be added after the Qt GUI event loop begins to set the DPI app.setAttribute(QtCore.Qt.AA_Use96Dpi)

?

In which file/line number should I place the app.setAttribute call?

**Comment by t-sommer** [comment] 2019-01-10 21:02
This line starts the event loop:

https://github.com/CATIA-Systems/FMPy/blob/master/fmpy/gui/__main__.py#L19

**Comment by chrbertsch** [comment] 2019-01-10 21:10
Naively putting 
>app.setAttribute(QtCore.Qt.AA_Use96Dpi)

in line 20 does not solve the problem ...

**Comment by t-sommer** [comment] 2019-01-10 21:12
You have to set the flag _before_ `app.exec_()` is called

**Comment by t-sommer** [comment] 2019-01-11 09:42
I can do it like this

```
from PyQt5.QtCore import Qt
app.setAttribute(Qt.AA_Use96Dpi)

sys.exit(app.exec_())
```

but it breaks the plot similar to what you experience...

**Comment by chrbertsch** [comment] 2019-01-11 10:18
For me this fixes the problem on the extended display
![image](https://user-images.githubusercontent.com/16363372/51027914-62e39000-1592-11e9-819e-a00a3abedb71.png)
but now I have the problem on the primary display
![image](https://user-images.githubusercontent.com/16363372/51027961-7989e700-1592-11e9-9e88-b79746d63da6.png)
where everything was fine before. Funny ...

**Closed** 2019-02-09 12:11 UTC

**Comment by chrbertsch** [comment] 2019-02-09 16:36
Is this this closed as "won't fix" or is there a solution? Thanks!

**Comment by t-sommer** [comment] 2019-02-10 11:31
It's an upstream problem. The only thing that seems to work is to use the same scaling settings for both screens as suggested in [this answer on StackOvervflow](https://stackoverflow.com/questions/45108069/pyqtgraph-axes-not-displaying-correctly).
